version: '3'
services:
  api:
    env_file:
      - "app/.env"
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/profile/api:v0.1
    ports:
      - "1270:8070"
    restart: always
    volumes:
      - ${LOGFILE}
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - net_poptape
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1271:5432"
    volumes:
      - poptape_profile_data:/var/lib/postgresql/data
    networks:
      - net_poptape
networks:
  net_poptape:
    external: true
volumes:
  poptape_profile_data:
  
